Pb\MarkManagement\Domain\Mark:
    type: entity
    table: mark
    fields:
        id:
            id: true
            type: string
            generator:
                strategy: NONE
        value:
            type: float
            nullable: false
        coefficient:
            type: integer
        label:
            type: string
    manyToOne:
        subject:
            targetEntity: Subject
            inversedBy: marks
            joinColumn:
                name: subject_id
                referencedColumnName: id
        student:
            targetEntity: Student
            inversedBy: marks
            joinColumn:
                name: student_id
                referencedColumnName: id
