Pb\MarkManagement\Domain\Student:
    type: entity
    fields:
        id:
            id: true
            type: string
            generator:
                strategy: NONE
        lastName:
            type: string
        firstName:
            type: string
    oneToMany:
        marks:
            targetEntity: Mark
            mappedBy: student