# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The type of the application to build.
type: php:7.1
build:
    flavor: composer

variables:
    env:
        # Tell Symfony to always install in production-mode.
        SYMFONY_ENV: 'prod'

# The hooks that will be performed when the package is deployed.
hooks:
    build: |
        rm web/app_dev.php
        rm web/app_test.php
        rm web/app_test_cached.php
        rm -rf var/cache/*
        php bin/console --env=prod --no-debug --ansi cache:clear --no-warmup
        php bin/console --env=prod --no-debug --ansi cache:warmup
        php bin/console --env=prod --no-debug --ansi assets:install
    deploy: |
        rm -rf var/cache/*
        php bin/console --env=prod doctrine:migrations:migrate --no-interaction

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `:`.
relationships:
    database: "mydatabase:postgresql"

# The size of the persistent disk of the application (in MB).
disk: 4096

# The mounts that will be performed when the package is deployed.
mounts:
    "/var/cache": "shared:files/cache"
    "/var/logs": "shared:files/logs"
    "/var/sessions": "shared:files/sessions"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "web"
            # The front-controller script to send non-static requests to.
            passthru: "/app.php"

runtime:
    extensions:
        - pdo_pgsql