homepage:
    path: /
    defaults:
        _controller: AppBundle:Default:index

mark_list:
    path: /mark/list
    defaults:
        _controller: Pb\MarkManagement\Infrastructure\UserInterface\Web\MarkController::listAction

mark_enter:
    path: /mark/enter
    defaults:
      _controller: Pb\MarkManagement\Infrastructure\UserInterface\Web\MarkController::enterAction