homepage:
    path: /
    defaults:
        _controller: Pb\MarkManagement\Infrastructure\UserInterface\Web\HomeController::indexAction


domain_list:
    path: /domain/list
    defaults:
        _controller: Pb\MarkManagement\Infrastructure\UserInterface\Web\DomainController::listAction

domain_enter:
    path: /domain/enter
    defaults:
      _controller: Pb\MarkManagement\Infrastructure\UserInterface\Web\DomainController::enterAction

mark_list:
    path: /mark/list
    defaults:
        _controller: Pb\MarkManagement\Infrastructure\UserInterface\Web\MarkController::listAction

mark_enter:
    path: /mark/enter
    defaults:
      _controller: Pb\MarkManagement\Infrastructure\UserInterface\Web\MarkController::enterAction

student_list:
    path: /student/list
    defaults:
      _controller: Pb\MarkManagement\Infrastructure\UserInterface\Web\StudentController::listAction

student_enter:
    path: /student/enter
    defaults:
      _controller: Pb\MarkManagement\Infrastructure\UserInterface\Web\StudentController::enterAction

student_academic_transcript:
    path: /student/{id}/academic_transcript
    defaults:
      _controller: Pb\MarkManagement\Infrastructure\UserInterface\Web\StudentController::academicTranscriptAction
