# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    ### Repository
    pb.domain.repository:
            class: 'Pb\MarkManagement\Infrastructure\Persistence\Doctrine\DomainRepository'
            arguments:
                - '@doctrine.orm.entity_manager'

    pb.domain.query:
        class: 'Pb\MarkManagement\Infrastructure\Persistence\Doctrine\ListDomainQuery'
        arguments:
            - '@doctrine.orm.entity_manager'

    pb.mark.repository:
        class: 'Pb\MarkManagement\Infrastructure\Persistence\Doctrine\MarkRepository'
        arguments:
            - '@doctrine.orm.entity_manager'

    pb.mark.query:
        class: 'Pb\MarkManagement\Infrastructure\Persistence\Doctrine\ListMarkQuery'
        arguments:
            - '@doctrine.orm.entity_manager'

    pb.student.query:
        class: 'Pb\MarkManagement\Infrastructure\Persistence\Doctrine\ListStudentQuery'
        arguments:
            - '@doctrine.orm.entity_manager'

    pb.academic_transcript.query:
        class: 'Pb\MarkManagement\Infrastructure\Persistence\Doctrine\AcademicTranscriptQuery'
        arguments:
            - '@doctrine.orm.entity_manager'

    pb.student.repository:
        class: 'Pb\MarkManagement\Infrastructure\Persistence\Doctrine\StudentRepository'
        arguments:
            - '@doctrine.orm.entity_manager'

    ### Command handler
    pb.student.handler.enter:
        class: 'Pb\MarkManagement\Application\Handler\EnterStudentHandler'
        arguments:
            - '@pb.student.repository'
        tags:
            - { name: command_handler, handles: enter_student }
    pb.domain.handler.enter:
        class: 'Pb\MarkManagement\Application\Handler\EnterDomainHandler'
        arguments:
            - '@pb.domain.repository'
        tags:
            - { name: command_handler, handles: enter_domain}
    pb.mark.handler.enter:
        class: 'Pb\MarkManagement\Application\Handler\EnterMarkHandler'
        arguments:
            - '@pb.mark.repository'
        tags:
            - { name: command_handler, handles: enter_mark }

    ### Fixture loading
    hautelook_alice.locator.env_directory:
        class: 'Pb\MarkManagement\Infrastructure\Persistence\Doctrine\Fixtures\FileLocator'
