# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    ### Repository
    pb.mark.repository:
        class: 'Pb\MarkManagement\Infrastructure\Persistence\Doctrine\MarkRepository'
        arguments:
            - '@doctrine.orm.entity_manager'

    pb.mark.query:
        class: 'Pb\MarkManagement\Infrastructure\Persistence\Doctrine\ListMarkQuery'
        arguments:
            - '@doctrine.orm.entity_manager'

    ### Command handler
    pb.mark.handler.enter:
        class: 'Pb\MarkManagement\Application\Handler\EnterMarkHandler'
        arguments:
            - '@pb.mark.repository'
        tags:
            - { name: command_handler, handles: enter_mark }
